### ISSUE TITLE
Missing source files for the plugin

### ISSUE THREAD

**Issue by efaraz27** [capacitor-community/advertising-id#10]
**Describe the bug**
maps for various JavaScript files (`definitions.js`, `index.js`, `web.js`) from the `@capacitor-community/advertising-id` package. The system reports that it cannot find the corresponding TypeScript source files (`definitions.ts`, `index.ts`, `web.ts`) at the specified directory paths. These warnings suggest missing source map references, which could potentially impact the debugging and development experience.

**To Reproduce**
- Ensure @capacitor-community/advertising-id is added to the project.
- Run the `npm start` or `yarn start` command
- Observe the terminal output during the build process.
- Notice multiple warning messages related to the missing TypeScript files for source map generation.

**Expected behavior**
The expected behavior is a clean build without warnings related to missing source files or source maps. The build process should successfully locate or not require the missing TypeScript files, ensuring that source maps properly link to existing source files to facilitate debugging and development.

**Screenshots**
<img width="753" alt="Screenshot 2024-02-20 at 4 25 55 PM" src="https://github.com/capacitor-community/advertising-id/assets/69633045/c9afda27-3504-4a45-a481-d30e7aff0c29">

**Desktop (please complete the following information):**
 - OS: iOS
 - Node Version: 18.12.1
 - Package Version: 5.0.0
 
**Smartphone (please complete the following information):**
N/A - This issue is related to the development/build process and does not directly affect smartphone environments.

**Additional context**
Web framework - React
Capacitor version - v5

**Comment by jcesarmobile** [comment]
can you provide a sample app? 
I can't reproduce on my app, I guess it depends on the build settings.
